# Generated by Django 5.1.3 on 2024-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0002_reporter_supervisor_worker_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='worker',
            name='job_title',
            field=models.CharField(choices=[('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CLEANER', 'Cleaner'), ('WASTE_DISPOSER', 'Waste Disposer'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
